name: rhubarb
channels:
  - defaults
  - kitsune.one # For belnder as module
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytest>=7.2.0
  - mypy
  - python-blender>=3.2 - #Blender as module ()
  - tomli
  - requests
  - debugpy
  - flask
  - numpy
  - black
  - pip:
    - -e .
    #- bpy>=3.2 # Official blender-as-module, only since 3.4 (no Audaspace)
    #- fake-bpy-module-3.3
    #- fake-bpy-module-latest