[project]
name = "rhubarb_lipsync"
version = "4.0.0"

[tool.setuptools]
packages = ["rhubarb_lipsync"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

# https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html