[project]
name = "rhubarb_lipsync"
version = "4.0.0"
license = "MIT"


[tool.rhubarb_lipsync]
platforms=["Linux", "macOS", "Windows"]

[tool.rhubarb_lipsync.download]
base_url = "https://github.com/DanielSWolf/rhubarb-lip-sync/releases"
base_name = "Rhubarb-Lip-Sync"
version="1.13.0"


[tool.setuptools]
packages = ["rhubarb_lipsync"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

 
# https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html