name: 🪲 Bug Report
description: When something is not working as expected.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        💡 Check the [Troubleshooting guide](troubleshooting.md).

        💡 Start Blender in debug mode from the command line: `blender --debug`. This will make the addon log messages with maximal verbosity, possibly giving more clues about the issue.

        💡 On Windows, go to the main menu: `Window/Toggle System Console` to open the console window.

        💡 You can make the plugin write logs directly to a file:
              - Go to the main menu: `Edit/Preferences/Add-ons`.
              - Find and expand `Animation: Rhubarb Lipsync NG`.
              - Set `Log File` to file-path. For example, `C:\temp\rhubarb.log`.

        

  - type: checkboxes
    attributes:
      label: Confirmation
      description: Please confirm you have followed the [Troubleshooting guide](troubleshooting.md).
      options:
        - label: I have followed the troubleshooting guide.
          required: true


  - type: textarea
    attributes:
      label: Summary
      description: |
          Explain the problem briefly below. Where it makes sense, include:
              - The steps to reproduce the issue.
              - What is the current vs. expected outcome.
              - Any error message or screenshot.
              - If it used to work in the previous version of the addon (regression), provide the last working version.
    validations:
      required: true

  - type: input
    attributes:
      label: Rhubarb Lipsync NG addon version
      description: |
        Addon version. Check the `.zip` file name you used to install the addon or in Blender: `Edit/Preferences/Add-ons`.
        Find and expand `Animation: Rhubarb Lipsync NG`.
      placeholder: "1.2.1, 1.3.1, 1.4.0, 1.4.1"

  - type: input
    attributes:
      label: Blender Version
      placeholder: "3.3.20, 3.4, 3.5, 3.6, 4.0, 4.1, 4.2"

  - type: input
    attributes:
      label: Operating System
      placeholder: Windows, Linux, macOS

