name: "Run junit tests"

on: [push]

jobs:
  unit-tests:
    name: Unit tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
      # "macos-latest" - No python module in conda https://anaconda.org/kitsune.ONE/python-blender/files
      # "windows-latest" - No os.fork method. Without forking some of the integration tests are failing.
        os: ["ubuntu-latest"]
        python-version: ["3.10", "3.11.3"]
    steps:        
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      # - uses: awalsh128/cache-apt-pkgs-action@latest
      #   with:
      #     packages: libxxf86vm1 libxfixes3 libxi6 libxkbcommon0 libgl1-mesa-glx
      #     #version: 1.0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' 
      
      - run: |
          sudo apt-get update
          sudo apt-get install -y libxxf86vm1 libxfixes3 libxi6 libxkbcommon0 libgl1-mesa-glx
      - name: Install dependencies
        run: |
          pip install pytest-xdist pytest-forked
          pip install bpy
          pip install -e .
      
      - name: Cache Downloads
        id: cache-download
        uses: actions/cache@v3
        with:
          path: download
          key: download-${{hashFiles('pyproject.toml')}}
      
      - name: Download rhubard binaries
        run: |
         cd scripts
         python rhubarb_bin.py
      - name: Run pytest
        run: pytest