name: "Junit tests"

on: [push]

jobs:
  unit-tests:
    name: Unit tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    # defaults:
    #   run:
    #     shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        #os: ["ubuntu-latest"]
        # , "3.11.3" - Only bpy 4.0.0 in pypi
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      # - uses: awalsh128/cache-apt-pkgs-action@latest
      #   with:
      #     packages: libxxf86vm1 libxfixes3 libxi6 libxkbcommon0 libgl1-mesa-glx
      #     #version: 1.0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

        # - name: Install System Dependencies (Ubuntu)
        # sudo apt-get install -y libxxf86vm1 libxfixes3 libxi6 libxkbcommon0 libgl1-mesa-glx
        # if: startsWith(matrix.os, 'ubuntu')
        # run: |
        #   sudo apt-get update
        #   sudo apt-get install -y libgl1-mesa-glx
      - name: Install dependencies
        run: |
          pip install pytest tomli
          pip install bpy
          pip install -e .

      - name: Cache Downloads
        id: cache-download
        uses: actions/cache@v4
        with:
          path: download
          key: download-${{hashFiles('pyproject.toml')}}

      - name: Download rhubard binaries
        run: |
         cd scripts
         python rhubarb_bin.py

      - name: Run pytest
        run: pytest --junitxml=pytest_junit_results.xml --tb=long

      - name: Test Report # https://github.com/dorny/test-reporter/issues/244
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Pytest
          path: pytest_junit_results.xml
          reporter: java-junit

